### ISSUE TITLE
type error in example

### ISSUE THREAD

**Issue by maiermic** [vardius/peer-data#10]
The [example](https://rafallorenz.com/peer-data/) on the website

```ts
import PeerData, { EventDispatcher, SocketChannel } from 'peer-data';

const servers = {
  iceServers: [
    {url: "stun:stun.1.google.com:19302"}
  ]
};

const dispatcher = new EventDispatcher();
const peerData = new PeerData(dispatcher, servers);
const signaling = new SocketChannel(dispatcher, 'http://localhost:8080');

room.on("participant", participant => {
  participant.on("message", payload => console.log("message", payload));

  participant.send('Hi mate! this is private message.');
})
```

compiles with errors in TypeScript 3.9.3

```
src/index.ts:10:43 - error TS2345: Argument of type '{ iceServers: { url: string; }[]; }' is not assignable to parameter of type 'RTCConfiguration'.
  Types of property 'iceServers' are incompatible.
    Type '{ url: string; }[]' is not assignable to type 'RTCIceServer[]'.
      Property 'urls' is missing in type '{ url: string; }' but required in type 'RTCIceServer'.

10 const peerData = new PeerData(dispatcher, servers);
                                             ~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:1291:5
    1291     urls: string | string[];
             ~~~~
    'urls' is declared here.

src/index.ts:13:1 - error TS2304: Cannot find name 'room'.

13 room.on("participant", participant => {
   ~~~~
```

**Comment by vardius** [comment]
https://github.com/vardius/peer-data/commit/5bc7dfb4466ccd72d33b5d3c6ffa18ec71f2f1fb

**Comment by maiermic** [comment]
There's still the first mistake:

```js
{url: "stun:stun.1.google.com:19302"}
```

Should be `urls` instead of `url` according to the type definition.

**Comment by vardius** [comment]
Fixed snippets with `urls` good catch. thanks

**Comment by maiermic** [comment]
Thanks for fixing it :slightly_smiling_face:
